Algoritmo "olamundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)  Ana Carolina Fantineli
// Data atual  : 28/03/2022

Var
// Seção de Declarações das variáveis 



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Olá mundo!")

Fimalgoritmo